CREATE DATABASE IF NOT EXISTS EVENT_ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS EVENT_ANALYTICS_DB.RAW;
CREATE SCHEMA IF NOT EXISTS EVENT_ANALYTICS_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS EVENT_ANALYTICS_DB.MART;

CREATE WAREHOUSE IF NOT EXISTS EVENT_ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;
