USE DATABASE EVENT_ANALYTICS_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE ORGANIZERS_RAW (
  ORGANIZER_ID NUMBER,
  ORGANIZER_NAME STRING,
  ORGANIZER_TYPE STRING,
  COUNTRY STRING,
  CREATED_AT DATE,
  UPDATED_AT DATE,
  LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RESELLERS_RAW (
  RESELLER_ID NUMBER,
  RESELLER_NAME STRING,
  CHANNEL STRING,
  COMMISSION_RATE FLOAT,
  CREATED_AT DATE,
  UPDATED_AT DATE,
  LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMERS_RAW (
  CUSTOMER_ID NUMBER,
  CUSTOMER_NAME STRING,
  EMAIL STRING,
  SEGMENT STRING,
  CITY STRING,
  COUNTRY STRING,
  CREATED_AT DATE,
  UPDATED_AT DATE,
  LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE EVENTS_RAW (
  EVENT_ID NUMBER,
  EVENT_NAME STRING,
  CATEGORY STRING,
  ORGANIZER_ID NUMBER,
  EVENT_CITY STRING,
  EVENT_COUNTRY STRING,
  EVENT_DATE DATE,
  CAPACITY NUMBER,
  BASE_TICKET_PRICE FLOAT,
  CREATED_AT DATE,
  UPDATED_AT DATE,
  LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TICKET_SALES_RAW (
  SALE_ID NUMBER,
  EVENT_ID NUMBER,
  CUSTOMER_ID NUMBER,
  RESELLER_ID NUMBER,
  SALE_DATE DATE,
  TICKET_TYPE STRING,
  QUANTITY NUMBER,
  UNIT_PRICE FLOAT,
  DISCOUNT_AMOUNT FLOAT,
  GROSS_REVENUE FLOAT,
  NET_REVENUE FLOAT,
  PAYMENT_STATUS STRING,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
